[package]
name = "kumpun-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
kumpun-core = { path = "../core" }
kumpun-schema = { path = "../schema" }
clap = { version = "4.5.36", features = ["derive"] }
serde_json = "1.0.140"

[dev-dependencies]
assert_cmd = "2.0.17"
predicates = "3.1.3"