[package]
name = "kumpun-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
kumpun-core = { path = "../core" }
kumpun-schemas = { path = "../schemas" }
clap = { version = "4.5.36", features = ["derive"] }

[dev-dependencies]
assert_cmd = "2.0.17"